### ISSUE TITLE
No way to create integer constants or types of parametric bit width without const_get

### ISSUE THREAD

**Issue by whitequark** [ruby-llvm/ruby-llvm#21]

**Comment by thoughtafter** [comment]
This has been fixed.

Create integer types with:

- `LLVM.i(width)`
- `LLVM::Type.i(width)`
- `LLVM::Type.integer(width)`

These are instances of LLVM::IntType.

Likewise LLVM::Float and LLVM:double are now instances of LLVM:RealType.
