### ISSUE TITLE
`inbounds_gep2` ignores the `type` argument

### ISSUE THREAD

**Issue by quentin** [ruby-llvm/ruby-llvm#251]
Hi, the `inbounds_gep2` method ignores the `type` argument because of this typo:

https://github.com/ruby-llvm/ruby-llvm/blob/cf1c5a50c083ffc2a04e1f708c7f729943d908de/lib/llvm/core/builder.rb#L636

`=` should be replaced with `||=`:

```ruby
type ||= must_infer_type!(ptr) 
```

This has a lot of implications in the generated code since `gep` computes the wrong displacement from pointer.

**Comment by quentin** [comment]
Also note that conversely to other builder method's, `gep2` has no default value for the `name` argument.

**Comment by thoughtafter** [comment]
Thank you. I think it's long overdue do have more builder tests, and dedicated `builder_test` file. I think I'll get this in soon and cut another LLVM 18 release. And then LLVM 19 will have this when it's released later this month.
