### ISSUE TITLE
parsing large integer constants fails

### ISSUE THREAD

**Issue by quentin** [ruby-llvm/ruby-llvm#262]
Hi, it is not possible to call `LLVM::Int256.parse()` with large numbers that do not fit `unsigned long long`. Probably any `LLVM::IntN` with `N > 64` is affected.

## Reproduction steps

To test, try adding this testcase in `test/value_test.rb`:
```ruby
[LLVM::Int256.parse("0x10000000000000000000000000000000000000000", 16), 'i256 100433627744264367661409086998267390166893441816585564061696'],
```

Triggers this error:
```
ruby-llvm/lib/llvm/core/type.rb:242:in 'LLVM::C.const_int': bignum too big to convert into 'unsigned long long' (RangeError)
        from ruby-llvm/lib/llvm/core/type.rb:242:in 'LLVM::IntType#from_i'
        from ruby-llvm/lib/llvm/core/type.rb:264:in 'LLVM::IntType#parse'
        from ruby-llvm/test/value_test.rb:117:in '<class:ValueTestCase>'
```

## Cause

The root cause is this code:

https://github.com/ruby-llvm/ruby-llvm/blob/66c3f7fac9812ad90e9dc59d3f3d4e05d60fe384/lib/llvm/core/type.rb#L262-L265

When the commented line 263 is used instead of 264, the testcase pass, but `poison` testcases fails.

## Workaround

Versions up to `18.1.8` are OK. Is there a workaround to parse large integers with `18.2.0` and later ?

**Comment by thoughtafter** [comment]
I can't think of a workaround, but you're correct that line 263 should be used but with correct handling for poison. I will investigate shortly

**Comment by thoughtafter** [comment]
#263 seems to fix this well enough for now. I will push it as part of 19.1.2 which I hope to release in a few hours.
