### ISSUE TITLE
Undefined Symbol Error

### ISSUE THREAD

**Issue by bryanjos** [ruby-llvm/ruby-llvm#36]
Hi, I'm trying out ruby-llvm and I'm getting the following error:

```
/home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ffi-1.9.3/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library '/home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ruby-llvm-3.4.0/ext/ruby-llvm-support/libRubyLLVMSupport-3.4.so': /home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ruby-llvm-3.4.0/ext/ruby-llvm-support/libRubyLLVMSupport-3.4.so: undefined symbol: _ZN4llvm3sys14DynamicLibrary7InvalidE (LoadError)
    from /home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ffi-1.9.3/lib/ffi/library.rb:100:in `map'
    from /home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ffi-1.9.3/lib/ffi/library.rb:100:in `ffi_lib'
    from /home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ruby-llvm-3.4.0/lib/llvm/support.rb:17:in `<module:C>'
    from /home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ruby-llvm-3.4.0/lib/llvm/support.rb:8:in `<module:Support>'
    from /home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ruby-llvm-3.4.0/lib/llvm/support.rb:5:in `<module:LLVM>'
    from /home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ruby-llvm-3.4.0/lib/llvm/support.rb:3:in `<top (required)>'
    from /home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ruby-llvm-3.4.0/lib/llvm.rb:5:in `require'
    from /home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ruby-llvm-3.4.0/lib/llvm.rb:5:in `<module:LLVM>'
    from /home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ruby-llvm-3.4.0/lib/llvm.rb:3:in `<top (required)>'
    from /home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ruby-llvm-3.4.0/lib/llvm/core.rb:1:in `require'
    from /home/bryanjos/.rvm/gems/ruby-2.1.1/gems/ruby-llvm-3.4.0/lib/llvm/core.rb:1:in `<top (required)>'
    from main.rb:3:in `require'
    from main.rb:3:in `<main>'
```

I'm on ubuntu and I built llvm from source with --enabled-shared and I'm using ruby 2.1.1 currently. I basically just made a test project using the hello world example from the samples folder in the repo. Any idea why I'm getting the error?

**Comment by mkfs** [comment]
You have to change the Rakefile in ext/ruby-llvm-support so that it invokes the --libs options of llvm-config :

    sh "#{CXX} -shared -lLLVM-#{LLVM_VERSION} #{task.prerequisites.join(' ')} " \
        "#{invoke_llvm_config('--cxxflags --ldflags --libs')} -o #{SUPPORT_LIB}"

Not sure if that is due to a change in GCC (making library name placement more strict) or in lvm-config (removing the LVM libraries from --ldflags).

I also had to rename `LLVMLoadLibraryPermanentl` to `LLVMLoadLibraryPermanently_rb` in ext/ruby-llvm-support/support.cpp and in lib/llvm/support.rb as it conflicts with a symbol in /usr/lib/llvm-3.4/lib/libLLVMSupport.a .

After making those changes, the top-level rake runs. Though there should probably be some code added to perform the rake in ext/ruby-llvm-support, or at least telling the user to do so since the README doesn't mention it.

**Comment by whitequark** [comment]
rake is ran when installing the gem.

**Comment by whitequark** [comment]
@mkfs That's not a proper fix to this issue. The issue arises from the new Ubuntu passing `-Wl,--as-needed` by default. What you did is to statically link most components of LLVM inside the support library, thus creating a "split brain situation" where you have two copies of LLVM executing side by side, each one with its own copy of global data.

The proper fix would be to reorder the LLVM library and the input objects:
      sh "#{CXX} -shared  #{task.prerequisites.join(' ')} -lLLVM-#{LLVM_VERSION} " \
         "#{invoke_llvm_config('--cxxflags --ldflags')} -o #{SUPPORT_LIB}"

I will commit a fix shortly.

**Comment by whitequark** [comment]
See 08cc699.

**Comment by mkfs** [comment]
<i>rake is ran when installing the gem.</i>

Running 'rake build' still gives this error:
  cannot load such file -- llvm/config
...meaning that rake has to be run manually in ext/ruby-llvm-support. I didn't try building with bundler, which I suppose I should have.

<i>The issue arises from the new Ubuntu passing -Wl,--as-needed by default.</i>

I figured it was something like that, but couldn't remember the standard fix (reordering the libraries) last night. Your version works correctly.

**Comment by whitequark** [comment]
This has nothing to do with bundler. `gem install` runs Rake in the proper place, see gemspec: https://github.com/ruby-llvm/ruby-llvm/blob/master/ruby-llvm.gemspec#L19

**Comment by mkfs** [comment]
Yes, I know -- it was in building the gem after the `git clone` that I had to run the ext/ruby-llvm-support directly. Can't gem install without a gem!
