### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by pmetzger** [ruby-llvm/ruby-llvm#49]
Is this project abandoned? I'd like to use it for some work I'm doing (a compiler front end prototype written in Ruby) but I need it to work with LLVM 4.0. Will I have to update it myself for that to happen?

If so, could someone give me a hint of what might be involved in doing that? There isn't much internal documentation in the code.

**Comment by whitequark** [comment]
You'll need to update versions (see https://github.com/ruby-llvm/ruby-llvm/commit/a06c3c9a5e3d8cdcb5f519ac2d6fa1bd4413f728) and re-run ffi_gen on 4.0.

**Comment by pmetzger** [comment]
Any other major changes required by the LLVM C API changes in the interim, or will I just need to poke at it? And if I do the work correctly, is it likely to be accepted back to the main project?

**Comment by whitequark** [comment]
> Any other major changes required by the LLVM C API changes in the interim, or will I just need to poke at it?

The JIT compiler API was broken, but https://github.com/ruby-llvm/ruby-llvm/issues/48 should fix it. The attribute API was changed, and I'll explain how to re-do it in the bindings.



> And if I do the work correctly, is it likely to be accepted back to the main project?

Sure, send a PR.

**Comment by thoughtafter** [comment]
The update to 3.8 was straightforward. I suspect the update to 4.0 will be as well. The JIT situation is complicated and not everyone will need that but it is needed internally for testing. I'm also using this library for a project and I'm interested in keeping it going.

**Comment by whitequark** [comment]
Closing the issue as the upgrade PRs are being merged now.
