### ISSUE TITLE
Problems running "rake generate_ffi" on Debian.

### ISSUE THREAD

**Issue by pmetzger** [ruby-llvm/ruby-llvm#52]
On Debian Jessie, with LLVM 4.0 installed in /usr/local, I'm trying to run "rake generate_ffi". I've hand edited version.rb and re-run the Rakefile in ext/ruby-llvm-support/ though I'm not sure if any other steps are needed.

When I run  "rake generate_ffi", I get:

/usr/include/x86_64-linux-gnu/sys/types.h:146:10: fatal error: 'stddef.h' file not found
rake aborted!

Not sure how to proceed from here.

Full errors:

/usr/include/x86_64-linux-gnu/sys/types.h:146:10:\` fatal error: 'stddef.h' file not found
rake aborted!
NoMethodError: undefined method \`[]' for nil:NilClass
/home/perry/.rvm/gems/ruby-2.4.1/gems/ffi_gen-1.2.0/lib/ffi_gen.rb:573:in \`read_declaration'
/home/perry/.rvm/gems/ruby-2.4.1/gems/ffi_gen-1.2.0/lib/ffi_gen.rb:346:in \`block in declarations'
/home/perry/.rvm/gems/ruby-2.4.1/gems/ffi_gen-1.2.0/lib/ffi_gen.rb:338:in \`each'
/home/perry/.rvm/gems/ruby-2.4.1/gems/ffi_gen-1.2.0/lib/ffi_gen.rb:338:in \`each_with_index'
/home/perry/.rvm/gems/ruby-2.4.1/gems/ffi_gen-1.2.0/lib/ffi_gen.rb:338:in \`declarations'
/home/perry/.rvm/gems/ruby-2.4.1/gems/ffi_gen-1.2.0/lib/ffi_gen/ruby_output.rb:10:in \`block in generate_rb'
/home/perry/.rvm/gems/ruby-2.4.1/gems/ffi_gen-1.2.0/lib/ffi_gen.rb:150:in \`indent'
/home/perry/.rvm/gems/ruby-2.4.1/gems/ffi_gen-1.2.0/lib/ffi_gen/ruby_output.rb:5:in \`generate_rb'
/home/perry/.rvm/gems/ruby-2.4.1/gems/ffi_gen-1.2.0/lib/ffi_gen.rb:280:in \`generate'
/home/perry/.rvm/gems/ruby-2.4.1/gems/ffi_gen-1.2.0/lib/ffi_gen.rb:745:in \`generate'
/home/perry/proj/ruby-llvm/Rakefile:44:in \`block (2 levels) in <top (required)>'
/home/perry/proj/ruby-llvm/Rakefile:43:in \`each'
/home/perry/proj/ruby-llvm/Rakefile:43:in \`block in <top (required)>'
/home/perry/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in \`<top (required)>'
Tasks: TOP => generate_ffi
(See full trace by running task with --trace)

**Comment by whitequark** [comment]
Something's screwy with the libclang include paths. If you port ffi_gen to newer clang (see #53) then it might just resolve itself. Seems easier than debugging it now to me.

**Comment by thoughtafter** [comment]
This might "just work" if you install the packages from here:

http://apt.llvm.org/

````
deb http://apt.llvm.org/jessie/ llvm-toolchain-jessie-4.0 main
deb-src http://apt.llvm.org/jessie/ llvm-toolchain-jessie-4.0 main
````

I'm doing this on a test system running Ubuntu 16.04 and rake generate_ffi works fine.

**Comment by thoughtafter** [comment]
I've updated master to LLVM 4.0 and created a llvm-4.0 branch to use. This should mean you no longer have to run rake generate_ffi yourself.
