### ISSUE TITLE
ruby-llvm can't be installed anymore on Mac with current stable version of Ruby and llvm?

### ISSUE THREAD

**Issue by eterps** [ruby-llvm/ruby-llvm#56]
`gem install ruby-llvm` gives the following error on ruby's current stable version on Mac:

```
Fetching: rake-10.5.0.gem (100%)
Successfully installed rake-10.5.0
Fetching: ffi-1.9.25.gem (100%)
Building native extensions. This could take a while...
Successfully installed ffi-1.9.25
Fetching: ruby-llvm-3.5.0.gem (100%)
Building native extensions. This could take a while...
ERROR:  Error installing ruby-llvm:
	ERROR: Failed to build gem native extension.

    current directory: /Users/erik/.gem/ruby/2.5.1/gems/ruby-llvm-3.5.0/ext/ruby-llvm-support
/Users/erik/.rubies/ruby-2.5.1/bin/ruby -rrubygems /Users/erik/.rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/exe/rake RUBYARCHDIR=/Users/erik/.gem/ruby/2.5.1/extensions/x86_64-darwin-17/2.5.0-static/ruby-llvm-3.5.0 RUBYLIBDIR=/Users/erik/.gem/ruby/2.5.1/extensions/x86_64-darwin-17/2.5.0-static/ruby-llvm-3.5.0
checking for llvm-config... rake aborted!
Cannot find llvm-config: tried ["llvm-config-3.5", "llvm-config"]
/Users/erik/.gem/ruby/2.5.1/gems/ruby-llvm-3.5.0/ext/ruby-llvm-support/Rakefile:24:in `check_for'
/Users/erik/.gem/ruby/2.5.1/gems/ruby-llvm-3.5.0/ext/ruby-llvm-support/Rakefile:29:in `find_llvm_config'
/Users/erik/.gem/ruby/2.5.1/gems/ruby-llvm-3.5.0/ext/ruby-llvm-support/Rakefile:53:in `<top (required)>'
```

`llvm-config` is installed though:

```
which llvm-config
/usr/local/opt/llvm/bin/llvm-config
/usr/local/opt/llvm/bin/llvm-config --version
6.0.1
```

## Steps to reproduce

```bash
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
$ curl -s https://www.ruby-lang.org/en/downloads/ |grep -i 'stable version'
The current stable version is 2.5.1.
$ brew install ruby-install
$ ruby-install ruby-2.5.1
$ brew install chruby
$ source /usr/local/opt/chruby/share/chruby/chruby.sh
$ chruby 2.5.1
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
$ brew install llvm --shared
$ export PATH="/usr/local/opt/llvm/bin:$PATH"
$ gem install ruby-llvm
```

**Comment by eterps** [comment]
Hmmm, it looks like this gem is only supposed to work with llvm 3.5, not 6.x or 7.x?

**Comment by eterps** [comment]
After searching some it seems that llvm 5.x is the highest supported version ( https://github.com/ruby-llvm/ruby-llvm/commits/master ). Although there is no updated release of this gem.

Seeing that the current `brew install llvm --shared` results in llvm 6.0.1 being installed I guess this is not going to work without installing an older version of llvm.

Installing older versions with brew isn't exactly easy it seems, see: https://danepowell.com/blog/homebrew-formula-versions

I am wondering how llvm support in other programming languages are handling this.

**Comment by eterps** [comment]
Apparently there is an easier way to install 'some' earlier versions:

```
brew search llvm
==> Formulae
llvm                                     llvm@3.7                                 llvm@3.9                                 llvm@4                                   llvm@5
brew install llvm@5 --shared
```

And by putting the latest git ref in your Gemfile:

```
gem 'ruby-llvm', git: 'https://github.com/ruby-llvm/ruby-llvm', ref: 'cc5195b'
```

You get at least a bit further:

```
export PATH="/usr/local/opt/llvm@5/bin:$PATH"
bundle
Fetching https://github.com/ruby-llvm/ruby-llvm
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using rake 12.3.1
Using bundler 1.16.3
Using ffi 1.9.25
Using minitest 5.11.3
Using minitest-color 0.0.2
Using ruby-llvm 5.0.0 from https://github.com/ruby-llvm/ruby-llvm (at cc5195b@cc5195b)
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/erik/.gem/ruby/2.5.1/bundler/gems/ruby-llvm-cc5195b74bfa/ext/ruby-llvm-support
/Users/erik/.rubies/ruby-2.5.1/bin/ruby -rrubygems /Users/erik/.gem/ruby/2.5.1/gems/rake-12.3.1/exe/rake
RUBYARCHDIR=/Users/erik/.gem/ruby/2.5.1/bundler/gems/extensions/x86_64-darwin-17/2.5.0-static/ruby-llvm-cc5195b74bfa
RUBYLIBDIR=/Users/erik/.gem/ruby/2.5.1/bundler/gems/extensions/x86_64-darwin-17/2.5.0-static/ruby-llvm-cc5195b74bfa
checking for llvm-config... llvm-config
checking for C++ compiler... g++
g++ -shared support.cpp -lLLVM-5.0 -I/usr/local/Cellar/llvm@5/5.0.2/include  -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings
-Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -DNDEBUG   -DLLVM_BUILD_GLOBAL_ISEL
-D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -L/usr/local/Cellar/llvm@5/5.0.2/lib -Wl,-search_paths_first -Wl,-headerpad_max_install_names  -o libRubyLLVMSupport-5.0.dylib
ld: library not found for -lLLVM-5.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
Command failed with status (1): [g++ -shared support.cpp -lLLVM-5.0 -I/usr/...]
/Users/erik/.gem/ruby/2.5.1/bundler/gems/ruby-llvm-cc5195b74bfa/ext/ruby-llvm-support/Rakefile:69:in `block in <top (required)>'
/Users/erik/.gem/ruby/2.5.1/gems/rake-12.3.1/exe/rake:27:in `<main>'
Tasks: TOP => default => libRubyLLVMSupport-5.0.dylib
(See full trace by running task with --trace)
```

**Comment by pmetzger** [comment]
@eterps As you have painfully learned, ruby-llvm has been largely abandoned for years. ☹️

**Comment by pmetzger** [comment]
I'm aware of the discussion when that commit was made, as I was a part of it. Believe me when I say this package is de facto abandoned. It's a shame, but it is true.

**Comment by whitequark** [comment]
I no longer use Ruby, so it'd be absurd to expect me to continue to maintain this. But I'll merge PRs.

**Comment by thoughtafter** [comment]
I can start a longer discussion on paths forward for this gem soon and separately.

As of right now the gem on rubygems and some of the documentation is out of date. However, the section on versioning is still correct. Version 3.5.0 is meant to be used with LLVM 3.5. The current code in this repository should work with LLVM 5.0, and I do have that working on my workstation which is Ubuntu 18.04. I do not have a mac environment to test.

If there is interest in updating to 6.0 that is a bit of a discussion but likely doable with caveats.

Again, without a mac environment I can't reproduce this but this seems to be key:
ld: library not found for -lLLVM-5.0

Here is what it looks like on my machine:

checking for llvm-config... llvm-config-5.0
checking for C++ compiler... g++
g++ -shared support.cpp -lLLVM-5.0 -I/usr/lib/llvm-5.0/include -std=c++0x -fuse-ld=gold -Wl,--no-keep-files-mapped -Wl,--no-map-whole-files -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -O2 -DNDEBUG  -fno-exceptions -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -L/usr/lib/llvm-5.0/lib   -o libRubyLLVMSupport-5.0.so

The relevant debian/ubuntu package is: llvm-5.0-dev.  Perhaps this is either a missing library or an incorrect library path. Can you determine where the library lives on your system?

**Comment by eterps** [comment]
This seems to work:

```
brew install llvm@5 --shared
ln -s /usr/local/opt/llvm\@5/lib/libLLVM.dylib /usr/local/opt/llvm\@5/lib/libLLVM-5.0.dylib
export LIBRARY_PATH='/usr/local/opt/llvm@5/lib'
$EDITOR Gemfile
  gem 'ruby-llvm', git: 'https://github.com/ruby-llvm/ruby-llvm', ref: 'cc5195b'
bundle install
Fetching https://github.com/ruby-llvm/ruby-llvm
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using rake 12.3.1
Using bundler 1.16.3
Using ffi 1.9.25
Using ruby-llvm 5.0.0 from https://github.com/ruby-llvm/ruby-llvm (at cc5195b@cc5195b)
Bundle complete! 3 Gemfile dependencies, 6 gems now installed.
```

The main issue seems to be the difference between how debian/ubuntu versions packages vs brew (i.e. `llvm@5/lib/libLLVM` vs `llvm-5.0/lib/libLLVM-5.0`.

@thoughtafter I don't think you need a Mac to reproduce this issue, using http://linuxbrew.sh would probably result in the same error.

Anyway, updating to 6.0 would probably be helpful as that is the current version installed by brew.

**Comment by thoughtafter** [comment]
One option would be to just add "-L/usr/local/opt/llvm@5/lib" to the command which builds libRubyLLVMSupport-5.0.so (ext/ruby-llvm-support/Rakefile). But before doing that I'd like to dive a bit deeper. This path is supposed to come from llvm-config.

On my machine:

llvm-config-5.0  --ldflags
returns:
-L/usr/lib/llvm-5.0/lib 

I'm curious as to what that returns using homebrew. @eterps can you test that?

**Comment by thoughtafter** [comment]
Okay, duh, @eterps  already pasted that above. Apparently llvm-config --ldflags gives this:

-L/usr/local/Cellar/llvm@5/5.0.2/lib

Is the library in that directory or not? If not, why is llvm-config reporting that directory? If so, why is the compiler failing?

That's not to say a workaround in this library wouldn't be a good idea. It would also be good to know if this is an upstream bug.

**Comment by eterps** [comment]
Yes, the library is in that directory:

```
$ ls /usr/local/Cellar/llvm@5/5.0.2/lib/libLLVM.*
/usr/local/Cellar/llvm@5/5.0.2/lib/libLLVM.dylib
```

**Comment by eterps** [comment]
Ah, the directory isn't the issue, but the filename is the problem, it literally expects `-5.0` in the library filename, this makes it work:

```
ln -s /usr/local/Cellar/llvm@5/5.0.2/lib/libLLVM.dylib /usr/local/Cellar/llvm@5/5.0.2/lib/libLLVM-5.0.dylib
```

**Comment by eterps** [comment]
@thoughtafter I added a check whether the libLLVM filename is versioned or not: https://github.com/ruby-llvm/ruby-llvm/pull/60

At least it makes the following possible on Mac:

```
$ brew install llvm@5 --shared
$ export PATH="/usr/local/opt/llvm@5/bin:$PATH"
$ echo "gem 'ruby-llvm', git: 'https://github.com/eterps/ruby-llvm', ref: '0fff123'" >Gemfile
$ bundle install
Fetching https://github.com/eterps/ruby-llvm
Resolving dependencies...
Using rake 12.3.1
Using bundler 1.16.3
Using ffi 1.9.25
Using ruby-llvm 5.0.0 from https://github.com/eterps/ruby-llvm (at 0fff123@0fff123)
Bundle complete! 1 Gemfile dependency, 4 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by thoughtafter** [comment]
This patch looks good so I've merged it. Everything still works fine on my system. Can you check the installation with the latest ref? If that goes smoothly I'll work on the documentation next.

**Comment by eterps** [comment]
@thoughtafter yes, installation works now with the latest ref, thanks.
Maybe you should wait with the documentation, there are still problems with recent refs besides installation: https://github.com/ruby-llvm/ruby-llvm/issues/61

I am closing this one.
