### ISSUE TITLE
Upgrade gem on rubygems.org

### ISSUE THREAD

**Issue by thoughtafter** [ruby-llvm/ruby-llvm#57]
Version 3.5.0 is the current version on rubygems:

https://rubygems.org/gems/ruby-llvm

This is likely to cause headaches and heartaches because it will only work with LLVM 3.5. The current code builds gem 5.0.0.

@whitequark would you be willing to either update the gem or add me as an owner? 

That seems the best first set of options.

**Comment by jvoorhis** [comment]
Hi @thoughtafter,

If you're willing to pick up the baton, send me a note at jvoorhis-at-gmail-com and I'll see what we can do. I haven't had the impetus or bandwidth to be actively involved as of late, but I appreciate the contributions.

Cheers,

J

**Comment by thetrung** [comment]
It's now LLVM 10.0.1, can anyone upgrade gem version ?

**Comment by thoughtafter** [comment]
I've created a new gem:
https://rubygems.org/gems/ruby-llvm-next

**Comment by whitequark** [comment]
@thoughtafter I seem to have missed this issue. If you tell me your email I can add you as a gem owner for `ruby-llvm`.

**Comment by thetrung** [comment]
@thoughtafter @whitequark great, this's great ..

**Comment by thoughtafter** [comment]
My email is thoughtafter@gmail.com

**Comment by whitequark** [comment]
I've added you as an owner.

**Comment by thoughtafter** [comment]
ruby-llvm has had versions 10 and 11 pushed to rubygems.

https://rubygems.org/gems/ruby-llvm
