### ISSUE TITLE
Update to LLVM-6

### ISSUE THREAD

**Issue by thoughtafter** [ruby-llvm/ruby-llvm#59]
I tried a "simple" upgrade of bindings to LLVM-6 and it seems that all JIT tests segfault which is pretty nasty. Of course, not all users need JIT and might be interested in just having updated bindings.

One of the big issues moving forward and maintaining this library is that Ruby-LLVM was built using FFI-Gen which is broken for LLVM releases after 4 and has not been updated since Jan 2015. See my bug report here: https://github.com/neelance/ffi_gen/issues/42

So fixing FFI-Gen would make this project much easier to maintain moving forward, but that's an additional task.

**Comment by XVilka** [comment]
I make sense to target LLVM-8.0 now.

**Comment by thoughtafter** [comment]
Indeed. I've updated the master branch to LLVM-8.
