### ISSUE TITLE
Documentation: Supported features

### ISSUE THREAD

**Issue by ShalokShalom** [ruby-llvm/ruby-llvm#63]
Hi there :)

How is the current state of the project?

Which features of the language are currently supported?

Thanks :D

**Comment by thoughtafter** [comment]
The master branch is currently functional for LLVM 8. It implements nearly all of the LLVM-C API. In my use I've noted very few LLVM features that are unavailable. I believe ruby-llvm is comparable to LLVM libraries in most other languages other than C++ as they all use LLVM-C as their basis.

**Comment by ShalokShalom** [comment]
Thanks a lot :hugs:
