### ISSUE TITLE
update to a recent version

### ISSUE THREAD

**Issue by phykos** [ruby-llvm/ruby-llvm#66]
LLVM3.6 is over 5 years old.
can we have an update to a recent version like LLVM10?

**Comment by thoughtafter** [comment]
The current code uses LLVM 8. Does that work for your needs?

**Comment by phykos** [comment]
Wait what?
I saw LLVM3 needed for build or something in the README

**Comment by thoughtafter** [comment]
The README information has been very out of date. It was on my to-do list to upgrade to LLVM 10 and that went smoothly. I've also updated the README. Enjoy.
